POST http://localhost:5000/pm/create-user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU

{
    "id": "1lvc0a60lb34lc5r",
    "username": "test",
    "email": "test@gmail.com",
    "first_name": "This",
    "last_name": "Is Test0",
    "birthday": "1990-01-02"
}

### 

POST http://localhost:5000/pm/create-user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU

{
    "id": "1lvc0a60lb34uxyh",
    "username": "test1",
    "email": "test1@gmail.com",
    "first_name": "This",
    "last_name": "Is Test1",
    "birthday": "1990-01-02"
}

###

POST http://localhost:5000/pm/create-user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU

{
    "id": "1lvc0a60lb3b1qow",
    "username": "test2",
    "email": "test2@gmail.com",
    "first_name": "This",
    "last_name": "Is Test2",
    "birthday": "1990-01-02"
}

###
POST http://localhost:5000/pm/create-user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU


{
    "id": "1lvc0a60lb3b0n2m",
    "username": "test3",
    "email": "test3@gmail.com",
    "first_name": "This",
    "last_name": "Is Test3",
    "birthday": "1990-01-02"
}

### 

POST http://localhost:5000/pm/create-conversation
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU

{
    "userId1": "1lvc0a60lb34lc5r",
    "userId2": "1lvc023klb57rs1i",
    "conversationName": "Quang"
}


### Create a message
POST http://localhost:5000/pm/create-message
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU

{
    "messageContent": "Hello Kien, this is the last message",
    "fromUserId": "1lvc0a60lb34lc5r",
    "conversationId": "1lvc0dc8lb59uyxs"
}

###

##Create a project
POST http://localhost:5000/pm/create-project
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImcycGM2NGc4bGJhaTE4MzEiLCJpYXQiOjE2NzAyNDIxMTksImV4cCI6MTY3MDMyODUxOX0.9wzUP0sAbGnCJsQpOR3Ocanfh1dL_gWKqOBJ6OX6Crc

{
    "userId": "g2pc64g8lbai1831",
    "teamId": "1",
    "projectName": "testProj"
}

GET http://localhost:5000/pm/get-conversations?userId=1lvc0a60lb34lc5r
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU
###

GET http://localhost:5000/pm/get-messages?conversationId=1lvc0dc8lb59s1df
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU

###
GET http://localhost:5000/pm/user?id=1lvc0a60lb34lc5r
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU

###

GET http://localhost:5000/pm/search-users?searchString=
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFsdmMwMjNrbGI0eGhwbGwiLCJpYXQiOjE2NzAwNDQxMzcsImV4cCI6MTY3MDEzMDUzN30.c64FGCWPqS_NdKf3NoQHzBKhNQSwozOlxvaT_yLfISU
