GET http://localhost:5001/
###
POST http://localhost:5001/auth/signup
Content-Type: application/json

{
    "username": "test",
    "email": "hoangndst@gmail.com",
    "password": "Hoang2002"
}

###

POST http://localhost:5001/auth/signin
Content-Type: application/json

{
    "username": "hoangndst",
    "password": "Hoang2002"
}