GET http://localhost:5001/
###
POST http://localhost:5001/signup
Content-Type: application/json

{
    "username": "test",
    "email": "test@gmail.com",
    "password": "Hoang2002"
}

###

POST http://localhost:5001/signin
Content-Type: application/json

{
    "username": "test",
    "password": "Hoang2002"
}