GET http://localhost:5001/
###
POST http://w42g4.int3306.freeddns.org/auth/signup
Content-Type: application/json

{
    "username": "test",
    "email": "hoangndst@gmail.com",
    "password": "Hoang2002"
}

###

POST http://w42g4.int3306.freeddns.org/auth/signin
Content-Type: application/json

{
    "username": "test",
    "password": "Hoang2002"
}

###

POST http://w42g4.int3306.freeddns.org/